### PR TITLE
Main

### PR DESCRIPTION
**Pull request by ShivamB25**
🐳 Add Docker support and update README for thumbnail generation

Enabled the Dockerized setup for the Plex preview thumbnail generation script, significantly easing the installation and setup process. Adapted the README with comprehensive instructions on how to use the new Docker setup, and included updated details on features, customization, and support. Environment variables and configurations are now managed via `.env` and `docker-compose.yaml` for simpler deployment and scalability.

🔧 Refactor Python script to use environment variables

Updated the Python script to load configurations from environment variables, improving flexibility and compatibility with Docker. This change allows for dynamic setting adjustments without modifying the script directly, aligning the script with best practices for environment-specific configurations.

✨ Create `.env.example` for quick configuration setup

Introduced an `.env.example` file to provide a template for users to define necessary environment variables, streamlining the configuration process for new users and enhancing user experience.

### CODE REVIEW

**Comment by ShivamB25** [comment]
I don't have a nvidia gpu to test this around. this should be working as much as i tried staying loyal to the documentation

**Comment by stevezau** [comment]
Hey @ShivamB25, this is great. I will review and test via nvidia GPU! Thanks!!

**Comment by stevezau** [comment]
closing in fav or https://github.com/stevezau/plex_generate_vid_previews/pull/32

**Comment by stevezau** [comment]
@ShivamB25 thanks, i took your PR and made a whole bunch of changes to support docker. It is now on the dockerhub

**Comment by stevezau** [comment]
All good, i tested it on my server...

**Pull request closed without merging**
