### PR TITLE
[Ideation] Added AMD graphics features

### PR DESCRIPTION
**Pull request by uyu423**
## Overview

This PR adds support for AMD graphics.

## Note

- This is still in the ideation stage and requires testing.
- Currently, I am unable to set up a testing environment, so I have only written the code.
- Someone else might have better ideas for my ideation, so I am opening this Pull Request as "Draft"

Thanks !

### CODE REVIEW

**Comment by stevezau** [comment]
@uyu423 thank you for your efforts and opening this PR. 

I only have a NVIDIA Card.. so I can test this PR using that card. Are you able to test with an AMD card?

**Comment by uyu423** [comment]
@stevezau 

Yes, I have a personal Docker environment running with AMD. Specifically, it’s running on a Ryzen AMD 8600G CPU with integrated Radeon 740M Graphics.

From the system logs of `plexmediaserver`, it appears to be using `vaapi`, so I expect that adding AMD-related functionality to this project should be feasible.

Currently, I’m occupied with work, so testing immediately is difficult. I should be able to test the proposed code in this PR over the weekend or when I have some free time 😭

**Comment by stevezau** [comment]
@uyu423 i just pushed a change to changes hwaccel to auto... I did this because depending on what card you have will depends if you should use hw or CPU.. so I let ffmpeg decide. 

I think this would also work for AMD devices now..

can you test v1.11?

**Comment by stevezau** [comment]
@uyu423 are you able to test this on an AMD GPU?

**Comment by stevezau** [comment]
@uyu423 i implemented AMD support but i don't know if it works. Can you test it when you get a min? It is added in vers 1.2

**Pull request closed without merging**
